train:
  _target_: src.datasets.ASVspoofDataset
  part: "train"
  data_dir: ${oc.env:ASVSPOOF_DIR,${hydra:runtime.cwd}/data/LA}
  max_len: ${collate_max_len}
  instance_transforms: ${transforms.instance_transforms.train}
dev:
  _target_: src.datasets.ASVspoofDataset
  part: "dev"
  data_dir: ${oc.env:ASVSPOOF_DIR,${hydra:runtime.cwd}/data/LA}
  max_len: ${collate_max_len}
  instance_transforms: ${transforms.instance_transforms.inference}
