device: "auto"
train: # метрики, которые считаются во время обучения
  - _target_: src.metrics.AccuracyMetric
    name: "TRAIN_Accuracy"
inference: # метрики, которые считаются во время инференса (eval)
  - _target_: src.metrics.AccuracyMetric
    name: "Accuracy"
