train:
  data_object: # имя тензора, к которому применяется трансформ
    _target_: torch.nn.Sequential # чтобы применить несколько трансформов подряд
    _args_:
      - _target_: src.transforms.LogSpectrogram
        n_fft: 1724
        win_length: 1724
        hop_length: 130
        window: blackman
        power: 2.0
        eps: 1e-8
        n_frames: 600
        crop: random
        pad_mode: repeat
inference:
  data_object:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.LogSpectrogram
        n_fft: 1724
        win_length: 1724
        hop_length: 130
        window: blackman
        power: 2.0
        eps: 1e-8
        n_frames: 600
        crop: first
        pad_mode: repeat
