defaults:
  - model: lcnn
  - metrics: accuracy
  - datasets: asvspoof_eval # инференс не должен идти по обучающим данным
  - dataloader: asvspoof
  - transforms: stft
  - _self_
collate_max_len: 77870
inferencer:
  device_tensors: ["data_object", "labels"] # какие тензоры класть на устройство (например, GPU)
  device: auto # имя устройства или "auto"
  use_amp: False
  amp_dtype: bfloat16
  save_path: "eval" # любое имя, можно назвать по датасету
  seed: 1
  cudnn_benchmark: False
  from_pretrained: "saved/lcnn_stft_600f/model_best.pth" # путь к обученной модели
