defaults:
  - model: lcnn
  - writer: cometml
  - metrics: accuracy
  - datasets: asvspoof
  - dataloader: asvspoof
  - transforms: stft
  - _self_
collate_max_len: 77870
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.5
  step_size: 7930
loss_function:
  _target_: src.loss.CELoss
  class_weights: [1.0, 8.84]
writer:
  project_name: "asvspoof-lcnn"
  workspace: null
  run_name: "lcnn_stft"
  loss_names: ["loss"]
trainer:
  log_step: 50
  n_epochs: 30
  epoch_len: null
  device_tensors: ["data_object", "labels"] # какие тензоры класть на устройство (например, GPU)
  resume_from: null # null или путь к каталогу чекпоинта с *.pth и config.yaml
  device: auto # имя устройства или "auto"
  use_amp: True
  amp_dtype: bfloat16
  max_grad_norm: 5
  skip_oom: True
  override: False # если True, предыдущий запуск с тем же именем будет перезаписан
  monitor: "min dev_EER"
  save_period: 5 # чекпоинт каждые save_period эпох вдобавок к лучшей эпохе
  early_stop: 10 # эпох до ранней остановки
  save_dir: "saved"
  seed: 1
  cudnn_benchmark: False
