defaults:
  - lcnn
  - override /datasets: one_batch_test
  - _self_
model:
  dropout: 0.0
dataloader:
  num_workers: 2
  persistent_workers: False
  batch_size: 16
lr_scheduler:
  step_size: 1000000
loss_function:
  class_weights: null
writer:
  run_name: "one_batch_test"
  mode: "offline"
trainer:
  log_step: 5
  n_epochs: 50
  use_amp: False
  override: True # если True, предыдущий запуск с тем же именем будет перезаписан
  early_stop: 50
  save_period: 50
