_target_: src.logger.CometMLWriter
project_name: "asvspoof-lcnn"
workspace: null # null -> берётся workspace из ~/.comet.config
run_name: "testing"
mode: "online" # при "offline" рядом с запуском пишется .zip вместо выгрузки
loss_names: ["loss"] # какие лоссы логировать (полезно для задач с несколькими лоссами, например GAN)
log_checkpoints: False # True, если нужно логировать чекпоинты в Comet ML
id_length: 32 # длина run_id; Comet требует буквенно-цифровой ключ из 32-50 символов
