_target_: src.logger.CometMLWriter
project_name: "asvspoof-lcnn"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["loss"] # какие лоссы логировать (полезно для задач с несколькими лоссами, например GAN)
log_checkpoints: False # True, если нужно логировать чекпоинты в Comet ML
id_length: 32 # длина run_id
